routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('employee', 'EmployeeController');

app/Employee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Employee;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $employees = Employee::all();
        //return $employees;
        return view('employees.index')->with('employees',$employees);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('employees.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $newEmployee = new Employee();
        $newEmployee->name = $request->name;
        $newEmployee->nim = $request->nim;
        $newEmployee->designation = $request->designation;
        $newEmployee->number = $request->number;
        $newEmployee->dob = $request->dob;

        $newEmployee->save();

        return redirect()->route('employee.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $employee = Employee::find($id);
        return view('employees.edit')->with('employee',$employee);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $employee = Employee::find($id);
        $employee->name = $request->name;
        $employee->nim = $request->nim;
        $employee->designation = $request->designation;
        $employee->number = $request->number;
        $employee->dob = $request->dob;

        $employee->save();

        return redirect()->route('employee.index');
    }
    
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Employee::destroy($id);
        return redirect()->route('employee.index');
    }
}

resources/views/employees/create.blade.php
@extends('layout')

@section('content')
    
<h1 class="mt-5" style="text-align: center;color: #076104;font-family: Bernard MT Condensed;">Tambah Data</h1>

<br>
<form action="{{route('employee.store')}}" method="POST">
    @csrf
    <div class="mb-3">
      <label for="inputNim" class="form-label">NIM </label>
      <input type="number" name='nim' class="form-control" id="inputNim" aria-describedby="emailHelp">
    </div>
    <div class="mb-3">
      <label for="exampleInputEmail1" class="form-label">Nama </label>
      <input type="text" name='name' class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    </div>
    <div class="mb-3">
      <label for="exampleInputPassword1" class="form-label">Alamat</label>
      <input type="text" name='designation' class="form-control" id="exampleInputPassword1">
    </div>
    <div class="mb-3">
      <label for="exampleInputPassword1" class="form-label">No HP</label>
      <input type="text" name='number' class="form-control" id="exampleInputPassword1">
    </div>
    <div class="mb-3">
      <label for="exampleInputPassword1" class="form-label">Tanggal Lahir</label>
      <input type="date" name='dob' class="form-control" id="exampleInputPassword1">
    </div>
    <button type="submit" class="btn btn-primary">Simpan</button>
  </form>

@endsection

resources/views/employees/edit.blade.php
@extends('layout')

@section('content')
<h1 class="mt-5" style="text-align: center;color: #076104;font-family: Bernard MT Condensed;">Update Data</h1>
<br>

    
<form action="{{route('employee.update',$employee->id)}}" method="POST">
    @method('PUT')
    @csrf
    <div class="mb-3">
      <label for="exampleInputEmail1" class="form-label">NIM</label>
      <input value="{{$employee->nim}}" type="number" name='nim' class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    </div>
    <div class="mb-3">
      <label for="exampleInputEmail1" class="form-label">Nama</label>
      <input value="{{$employee->name}}" type="text" name='name' class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    </div>
    <div class="mb-3">
      <label for="exampleInputPassword1" class="form-label">Alamat</label>
      <input value="{{$employee->designation}}" type="text" name='designation' class="form-control" id="exampleInputPassword1">
    </div>
    <div class="mb-3">
      <label for="exampleInputPassword1" class="form-label">No HP</label>
      <input value="{{$employee->number}}" type="text" name='number' class="form-control" id="exampleInputPassword1">
    </div>
    <div class="mb-3">
      <label for="exampleInputPassword1" class="form-label">Tanggal Lahir</label>
      <input value="{{$employee->dob}}" type="date" name='dob' class="form-control" id="exampleInputPassword1">
    </div>
    <button type="submit" class="btn btn-primary">Simpan</button>
  </form>

@endsection

resources/views/employees/index.blade.php
@extends('layout')

@section('content')

<nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#" style="color: #076104;font-size: 35px;font-family: Bernard MT Condensed;">
      <img src="{{ asset('assets/uim.jpg') }}" alt="" width="65" height="45" class="d-inline-block align-text-top">
      Data Mahasiswa Kelas TI-B 2019
    </a>
  </div>
</nav>
  <br>  
<a href="{{route('employee.create')}}" class="btn btn-primary"style="text-align: left;">Tambah Data</a>
<table class="table">

    <tr>
        <th>No</th>
        <th>NIM</th>
        <th>Nama</th>
        <th>Alamat</th>
        <th>No HP</th>
        <th>Tanggal Lahir</th>
        <th>&emsp;&emsp;&ensp;Aksi</th>
    </tr>

    @foreach ($employees as $key => $employee)
    <tr>
        <td>{{ $key+1 }}</td>
        <td>{{$employee->nim}}</td>
        <td>{{$employee->name}}</td>
        <td>{{$employee->designation}}</td>
        <td>{{$employee->number}}</td>
        <td>{{$employee->dob}}</td>
        <td>
            <a href="{{route('employee.edit',$employee->id)}}" class="btn btn-sm btn-outline-primary" >Update</a>
            <form style="display:inline;" action="{{route('employee.destroy',$employee->id)}}" method="POST">
            @csrf
            @method('DELETE')
            <button type="submit" class="btn btn-sm btn-outline-danger">Delete</button>
            </form>
        </td>
    </tr> 
    @endforeach


</table>



@endsection

resources/views/layout.blade.php
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>Employee App</title>
  </head>
  <body>
    <div class="container">

        @yield('content')
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
  </body>
</html>